export default [
    { name: 'folder_name' },
    { name: 'common_name', cast: 'text[]' },
    { name: 'common_name_de', cast: 'text[]' },
    { name: 'binomial_name' },
    { name: 'genus' },
    { name: 'family' },
    { name: 'subfamily' },
    { name: 'edible_uses' },
    { name: 'medicinal_uses' },
    { name: 'material_uses_and_functions' },
    { name: 'botanic' },
    { name: 'propagation' },
    { name: 'cultivation' },
    { name: 'environment' },
    { name: 'material_uses' },
    { name: 'functions' },
    { name: 'provides_forage_for' },
    { name: 'provides_shelter_for' },
    { name: 'hardiness_zone' },
    { name: 'heat_zone' },
    { name: 'water' },
    { name: 'sun' },
    { name: 'shade' },
    { name: 'soil_ph', cast: 'soil_ph[]' },
    { name: 'soil_texture', cast: 'soil_texture[]' },
    { name: 'soil_water_retention', cast: 'soil_water_retention[]' },
    { name: 'environmental_tolerances', cast: 'text[]' },
    { name: 'native_climate_zones' },
    { name: 'adapted_climate_zones' },
    { name: 'native_geographical_range' },
    { name: 'native_environment' },
    { name: 'ecosystem_niche' },
    { name: 'root_zone_tendancy', cast: 'root_zone_tendancy' },
    { name: 'deciduous_or_evergreen', cast: 'deciduous_or_evergreen' },
    { name: 'herbaceous_or_woody', cast: 'herbaceous_or_woody' },
    { name: 'life_cycle', cast: 'life_cycle[]' },
    { name: 'growth_rate', cast: 'growth_rate' },
    { name: 'mature_size_width' },
    { name: 'mature_size_height' },
    { name: 'fertility', cast: 'fertility[]' },
    { name: 'pollinators' },
    { name: 'flower_colour' },
    { name: 'flower_type', cast: 'flower_type' },
    { name: 'has_drought_tolerance' },
    { name: 'tolerates_wind' },
    { name: 'plant_references', cast: 'text[]' },
    { name: 'is_tree' },
];
