# https://pre-commit.com/
repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: doc format
        exclude: ^frontend/
  # Frontend hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: frontend format
        args:
          [
            --config=frontend/prettier.config.js,
            --ignore-path=frontend/.prettierignore,
          ]
        files: ^frontend/
        types_or:
          - javascript
          - jsx
          - ts
          - tsx
          - json
          - css
          - scss
          - markdown
        additional_dependencies:
          - prettier@2.8.8
          - prettier-plugin-tailwindcss@0.2.1
          - "@trivago/prettier-plugin-sort-imports"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.24.0
    hooks:
      - id: eslint
        name: frontend lint
        args:
          [
            --config=frontend/.eslintrc.js,
            --max-warnings=0,
            --ignore-path=frontend/.eslintignore,
          ]
        verbose: true
        files: ^frontend/
        types: [file]
        types_or:
          - javascript
          - jsx
          - ts
          - tsx
        additional_dependencies:
          - eslint@8.24.0
          - eslint-plugin-react@7.31.8
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-storybook@0.6.11
  # Backend hooks
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: backend format
        args: [--manifest-path=backend/Cargo.toml]
        files: ^backend/
        pass_filenames: false
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.0.2
    hooks:
      - id: sqlfluff-fix
        name: sql format
        args: [--config=backend/.sqlfluff]
  - repo: https://github.com/nvuillam/npm-groovy-lint
    rev: v11.1.1
    hooks:
      - id: fix-npm-groovy-lint
        name: Fix Lint groovy findings
        description: Groovy & Jenkinsfile Auto-fixer
        entry: npm-groovy-lint --fix ci/Jenkinsfile ci/Jenkinsfile.release --failon warning --loglevel warning
  - repo: https://github.com/nvuillam/npm-groovy-lint
    rev: v11.1.1
    hooks:
      - id: format-npm-groovy-lint
        name: Format groovy findings
        description: Groovy & Jenkinsfile Auto-formatter
        entry: npm-groovy-lint --format ci/Jenkinsfile ci/Jenkinsfile.release
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --statistics
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        # Scan all .md files, exclude folders /meetings & /reports.
        files: ^(?!.*\/(meetings|reports)\/).*\.md$
        args: [-L crate]
        stages: [manual]
