-- This file should undo anything in `up.sql`
DROP TABLE plant_detail;
DROP TYPE IF EXISTS WATER;
DROP TYPE IF EXISTS SUN;
DROP TYPE IF EXISTS SHADE;
DROP TYPE IF EXISTS SOIL_PH;
DROP TYPE IF EXISTS SOIL_TEXTURE;
DROP TYPE IF EXISTS SOIL_WATER_RETENTION;
DROP TYPE IF EXISTS LIFE_CYCLE;
DROP TYPE IF EXISTS GROWTH_RATE;
DROP TYPE IF EXISTS FERTILITY;
DROP TYPE IF EXISTS FLOWER_TYPE;
DROP TYPE IF EXISTS HERBACEOUS_OR_WOODY;
DROP TYPE IF EXISTS ROOT_ZONE_TENDANCY;
DROP TYPE IF EXISTS DECIDUOUS_OR_EVERGREEN;
DROP TYPE IF EXISTS NUTRITION_DEMAND;