-- This file should undo anything in `up.sql`

DROP TABLE plant_detail;

DROP TYPE IF EXISTS WATER;
DROP TYPE IF EXISTS SUN;
DROP TYPE IF EXISTS SHADE;
DROP TYPE IF EXISTS SOIL_PH;
DROP TYPE IF EXISTS SOIL_TEXTURE;