name: 💡 Left over Issues
description: PermaplanT left over issues
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Tasks
      description: A list of what is missing
      value: " - [ ] \n - [ ] \n - [ ] \n - [ ] \n - [ ] \n - [ ] "
    validations:
      required: false

  - type: textarea
    attributes:
      label: Use case
      description: Which use case they refer to
    validations:
      required: false

  - type: input
    attributes:
      label: Related Pull request
      placeholder: "#543 leave it blank for now, insert it later"
    validations:
      required: false
