/*
 Generated by typeshare 1.0.0
*/

export interface NewSeed {
	name: string;
	variety_id: number;
	harvest_year: number;
	quantity: string;
	tags: string[];
	use_by?: Date;
	origin?: string;
	taste?: string;
	yield_?: string;
	generation?: number;
	quality?: string;
	price?: number;
	notes?: string;
}

