version: "3.8"

services:
  db:
    image: postgis/postgis:13-3.1
    restart: unless-stopped
    volumes:
      - postgis-data-dev:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pg
    restart: unless-stopped
    volumes:
      - pgadmin-data-dev:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"

volumes:
  pgadmin-data-dev:
    external: false
  postgis-data-dev:
    external: false
