/**
 * This file contains the mapping between the PermaPeople column names and the
 * column names of the database.
 */
export default {
  id: null,
  name: {
    map: 'common_name',
    priority: 'permapeople',
  },
  slug: null,
  description: null,
  created_at: null,
  updated_at: null,
  scientific_name: {
    map: 'binomial_name',
    priority: 'permapeople',
  },
  parent_id: null,
  version: null,
  type: null,
  link: null,
  wildflower: null,
  usda_hardiness_zone: {
    map: 'hardiness_zone',
    priority: 'permapeople',
  },
  life_cycle: {
    map: 'life_cycle',
    priority: 'permapeople',
  },
  light_requirement: {
    map: 'sun',
    priority: 'permapeople',
  },
  water_requirement: {
    map: 'water',
    priority: 'permapeople',
  },
  soil_type: {
    map: 'soil_texture',
    priority: 'permapeople',
  },
  height: {
    map: 'mature_size_height',
    priority: 'permapeople',
  },
  layer: null,
  edible_parts: null,
  propagation_method: null,
  wikipedia: null,
  growth: {
    map: 'growth_rate',
    priority: 'permapeople',
  },
  alternate_name: null,
  family: {
    map: 'family',
    priority: 'permapeople',
  },
  german_name: {
    map: 'common_name_de',
    priority: 'permapeople',
  },
  edible_uses: {
    map: 'edible_uses',
    priority: 'permapeople',
  },
  plants_for_a_future: null,
  medicinal: {
    map: 'medicinal_uses',
    priority: 'permapeople',
  },
  soil_ph: {
    map: 'soil_ph',
    priority: 'permapeople',
  },
  propagation_transplanting: null,
  germination_time: null,
  when_to_sow_outdoors: null,
  utility: null,
  edible: null,
  native_to: null,
  introduced_into: null,
  plants_of_the_world_online_link: null,
  plants_of_the_world_online_name_synonym: null,
  plants_of_the_world_online_link_synonym: null,
  seed_viability: null,
  when_to_plant_transplant: null,
  days_to_maturity: null,
  spacing: null,
  germination_temperature: null,
  when_to_start_outdoors_weeks: null,
  days_to_harvest: null,
  when_to_sow_indoors: null,
  '1000_seed_weight_g': null,
  seed_planting_depth: null,
  dutch_name: null,
  leaves: null,
  warning: null,
  root_type: null,
  when_to_plant_cuttings: null,
  drought_resistant: {
    map: 'has_drought_tolerance',
    priority: 'permapeople',
  },
  habitat: {
    map: 'environment',
    priority: 'permapeople',
  },
  cold_stratification_temperature: null,
  cold_stratification_time: null,
  genus: {
    map: 'genus',
    priority: 'permapeople',
  },
  danish_name: null,
  root_depth: {
    map: 'root_zone_tendency',
    priority: 'permapeople',
  },
  medicinal_parts: null,
  when_to_plant_division: null,
  propagation_direct_sowing: null,
  when_to_harvest: null,
  when_to_start_indoors_weeks: null,
  spread: null,
  pollination: null,
  pests: null,
  diseases: null,
  propagation_cuttings: null,
  french_name: null,
  alternate_scientific_name: null,
  hortipedia: null,
  invasive_in: null,
  years_to_bear: null,
  useful_tropical_plants: null,
  thinning: null,
  resistance: null,
  light_tolerance: null,
  chill_hours: null,
  beef_tomato: null,
  invasive: null,
};
