/**
 * This file contains the database columns and their corresponding types
 */
export default [
  { name: 'common_name_en', cast: 'text[]' },
  { name: 'common_name_de', cast: 'text[]' },
  { name: 'scientific_name' },
  { name: 'genus' },
  { name: 'family' },
  { name: 'subfamily' },
  { name: 'edible_uses' },
  { name: 'medicinal_uses' },
  { name: 'material_uses_and_functions' },
  { name: 'botanic' },
  { name: 'cultivation' },
  { name: 'environment' },
  { name: 'material_uses' },
  { name: 'functions' },
  { name: 'provides_forage_for' },
  { name: 'provides_shelter_for' },
  { name: 'hardiness_zone' },
  { name: 'heat_zone' },
  { name: 'shade' },
  { name: 'soil_ph', cast: 'soil_ph[]' },
  { name: 'soil_water_retention', cast: 'soil_water_retention[]' },
  { name: 'environmental_tolerances', cast: 'text[]' },
  { name: 'native_climate_zones' },
  { name: 'adapted_climate_zones' },
  { name: 'native_geographical_range' },
  { name: 'native_environment' },
  { name: 'ecosystem_niche' },
  { name: 'root_zone_tendancy', cast: 'root_zone_tendancy' },
  { name: 'deciduous_or_evergreen', cast: 'deciduous_or_evergreen' },
  { name: 'herbaceous_or_woody', cast: 'herbaceous_or_woody' },
  { name: 'life_cycle', cast: 'life_cycle[]' },
  { name: 'mature_size_width' },
  // { name: 'height' },
  { name: 'fertility', cast: 'fertility[]' },
  { name: 'pollinators' },
  { name: 'flower_colour' },
  { name: 'flower_type', cast: 'flower_type' },
  { name: 'tolerates_wind' },
  { name: 'plant_references', cast: 'text[]' },
  { name: 'is_tree' },
  { name: 'nutrition_demand', cast: 'nutrition_demand' },
  { name: 'article_last_modified_at' },
  { name: 'light_requirement', cast: 'light_requirement[]' },
  { name: 'water_requirement', cast: 'water_requirement[]' },
  { name: 'propagation_method', cast: 'propagation_method[]' },
  { name: 'growth', cast: 'growth[]' },
  { name: 'alternate_name', cast: 'text[]' },
  { name: 'beef_tomato' },
  { name: 'chill_hours', cast: 'integer' },
  { name: 'danish_name' },
  { name: 'diseases' },
  { name: 'drought_resistant', cast: 'boolean' },
  { name: 'dutch_name' },
  { name: 'edible', cast: 'boolean' },
  { name: 'edible_parts', cast: 'text[]' },
  { name: 'french_name' },
  { name: 'germination_temperature', cast: 'integer' },
  { name: 'hortipedia' },
  { name: 'introduced_into' },
  { name: 'invasive', cast: 'boolean' },
  { name: 'invasive_in' },
  { name: 'layer' },
  { name: 'leaves' },
  { name: 'light_tolerance' },
  { name: 'link' },
  { name: 'medicinal_parts' },
  { name: 'native_to' },
  { name: 'plants_for_a_future' },
  { name: 'plants_of_the_world_online_link' },
  { name: 'plants_of_the_world_online_link_synonym' },
  { name: 'plants_of_the_world_online_name_synonym' },
  { name: 'pollination' },
  { name: 'propagation_cuttings', cast: 'boolean' },
  { name: 'propagation_direct_sowing', cast: 'boolean' },
  { name: 'propagation_transplanting', cast: 'boolean' },
  { name: 'resistance' },
  { name: 'root_depth' },
  { name: 'root_type' },
  { name: 'seed_planting_depth' },
  { name: 'seed_viability' },
  { name: 'slug' },
  { name: 'soil_type', cast: 'soil_type[]' },
  { name: 'spread' },
  { name: 'thining' },
  { name: 'type' },
  { name: 'useful_tropical_plants' },
  { name: 'utility' },
  { name: 'warning' },
];
