//TODO #1123 - Some types will be generated by backend in the future
export type DrawingShapeType = 'rectangle' | 'ellipse' | 'freeLine' | 'bezierPolygon';

export type DrawingProperties = Record<string, string | number | number[] | number[][]>;

export type RectangleProperties = {
  width: number;
  height: number;
};

export type EllipseProperties = {
  radiusX: number;
  radiusY: number;
};

export type FreeLineProperties = {
  points: number[][];
};
